# Simple workflow for deploying static content to GitHub Pages
name: Build

on:
  push:
    branches: ["main"]
jobs:
  build:
    name: my-job
    runs-on: ubuntu-latest
    steps:
      # ...
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      # run any `bun` or `bunx` command
      - run: bun install
      - run: bun build ./index.html --minify --outdir=./dist
